### ISSUE TITLE
CUDA out of memory when using the network to train

### ISSUE THREAD

**Issue by nubma** [echocatzh/MTFAA-Net#4]
Hello,

First of all, thank you for proving the implementation. It was very helpful to understand the paper.

I had one question though. When I was trying to train the network using 30-second 48kHz audio, I always run into CUDA out of memory error, even if the batch size is set to 1. Have you seen that in your experiments or do you have any advice maybe?

Anything will be greatly appreciated!

**Comment by nubma** [comment]
After some debugging, it seems this line:

t_score = torch.einsum('bcft, bcfy->bfty', [qt, kt]) / (self.d_c**0.5)

in asa.py file occupied a lot of memory at the first TFCM+ASA modules after band merging. I would see memory usage jumped from about 2GB to 10GB, and that cannot be deleted or cache emptied for some reason.

**Comment by echocatzh** [comment]
Thanks for your attention,

I think 30-second may be too long, especially using attention structure which needs more memory for long audio. You could remove the t-attention or use shorter segments.

**Comment by nubma** [comment]
Ahhh, thank you for the suggestions! I will try them out
