### ISSUE TITLE
about ERB band filter bank

### ISSUE THREAD

**Issue by jzi040941** [echocatzh/MTFAA-Net#5]
Hi! Iwonder if we can reduce nerb which is currently using 256. I think if it has less number of bands it can reduce IOPS.
![image](https://user-images.githubusercontent.com/10007781/187367340-eeaf9d2f-080d-418d-a4e5-5f34f79776d4.png)
based on Baidu paper, I guess they are using ERB Bands applied in [10].

![image](https://user-images.githubusercontent.com/10007781/187367662-737f839d-d274-444c-b6e7-8184766053cc.png)

As I noticed in [PercepNet paper(A Perceptually-Motivated Approach for Low-Complexity, Real-Time
Enhancement of Fullband Speech)](https://arxiv.org/pdf/2008.04259.pdf) they are using 34 bands with 20khz highest frequency.

**Comment by stonelazy** [comment]
This seems to be a valid question. If i may know the solution for this please ?

**Comment by jzi040941** [comment]
![image](https://user-images.githubusercontent.com/10007781/187392957-e3d48e85-4fa5-4736-8bee-a0105742e7b3.png)
I Found that they used 256 number of erb bands in implementation section. my fault.

**Comment by echocatzh** [comment]
Hi jzi040941, 

Thanks for your attention, the `spafe` toolkit provides such ERB filter banks which I didn't use in the repo. In my opinion, feature compression processing such as ERB-scale or Bark-scale **cannot simply be inversed by `th.pinverse`**, this may not work. The inverse processing (from compressed feature to raw) like percep-net you given is a better way to deal with it.

In conclusion, please note some details of the feature inverse process.

Any suggestions are welcome!
