### ISSUE TITLE
erb.py reported a error :expected np.ndarray (got tuple)

### ISSUE THREAD

**Issue by FragrantRookie** [echocatzh/MTFAA-Net#6]
The report is as follows:
```
  File "E:/code_paper/MTFAA-Net-main/erb.py", line 24, in __init__
    filter = th.from_numpy(filter).float()
TypeError: expected np.ndarray (got tuple)
```

The error occurred on line 24 of erb.py.
`filter = th.from_numpy(filter).float()`
"filter" is a tuple has two members.

My Python version is 3.9.12.
My spafe version is 0.2.0.
My torch version is 1.12.1.

Hope you can teach me.

**Comment by echocatzh** [comment]
I can not reproduce it, if you figure it out, please let me know.

**Comment by FragrantRookie** [comment]
installed spafe-0.1.2.Not 0.2.0
