### ISSUE TITLE
Did you normalize signals when you calculate loss?

### ISSUE THREAD

**Issue by YangangCao** [echocatzh/MTFAA-Net#7]
Hi, thanks for you great work.
I find that the loss decrease hardly  when I train your MTFAA, I dont normalize signals when I calculate loss. 
Maybe I should normalize signals like 《Data augmentation and loss normalization for deep noise suppression》，I want to know your way to calculate loss.

**Comment by echocatzh** [comment]
Hi Yanggang, thanks for your attention, 

I'm not sure if normalized signals work, in the paper, the loss seems to be an extension of MSE.
